/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RtspVideo {
        "apiUrl": string;
        "authName": string;
        "authPass": string;
        "host": string;
        "mode": string;
        "port": string;
        /**
          * The last name
         */
        "src": string;
    }
}
declare global {
    interface HTMLRtspVideoElement extends Components.RtspVideo, HTMLStencilElement {
    }
    var HTMLRtspVideoElement: {
        prototype: HTMLRtspVideoElement;
        new (): HTMLRtspVideoElement;
    };
    interface HTMLElementTagNameMap {
        "rtsp-video": HTMLRtspVideoElement;
    }
}
declare namespace LocalJSX {
    interface RtspVideo {
        "apiUrl"?: string;
        "authName"?: string;
        "authPass"?: string;
        "host"?: string;
        "mode"?: string;
        "port"?: string;
        /**
          * The last name
         */
        "src"?: string;
    }
    interface IntrinsicElements {
        "rtsp-video": RtspVideo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rtsp-video": LocalJSX.RtspVideo & JSXBase.HTMLAttributes<HTMLRtspVideoElement>;
        }
    }
}
